### ISSUE TITLE
answer to a specific question

### ISSUE THREAD

**Issue by komangulo** [madingess/EasyApplyBot#31]
good morning friend,
in which section and in which line (how can I if possible in detail) make the bot answer the following question or similar in spanish:

how many years of experience do you have in cybersecurity?
 or

how many years of experience do you have in the following technology "x"?

Thank you very much for the tool

**Comment by madingess** [comment]
Hello Komangulo, 

Simply add a line in the `config.yaml` file under the `experience` section with the tool or  technology.

Ex:
```yaml
experience:
  ...
  cybersecurity: 4
  ...
  default: 0
```
